### PR TITLE
Tweaked descriptions – Part 11

### PR DESCRIPTION
**Pull request by 4Luke4**
A (small) collection of tweaks, fixes, and additions.

### CODE REVIEW

**Comment by 4Luke4** [comment]
In particular:
- Op#18: clarified new EE v2.6 behavior.
- Op#12: clarified new EE v2.6 behavior.
- VVC: "Drawing (0x18)", BIT15: "Scale/Center to view" and "Color Adjustment (0x1a)", BIT8: "Blend with character's 'Major' color".
- "CLEARAIR.2da": updated to EE v2.6.
- "MISSILE.ids": updated to EE v2.6.
- "PROJECTL.ids": updated to EE v2.6.

**Comment by lynxlynxlynx** [comment]
Hmm, what's that old history doing in there? Just a bad merge?

**Comment by 4Luke4** [comment]
> Hmm, what's that old history doing in there? Just a bad merge?

I probably messed things when fetching upstream...

Anyway, I noticed you can now fetch upstream directly here on GitHub, so that will hopefully be clearer/easier than using CLI and Git...

**Comment by lynxlynxlynx** [comment]
I'll just squash it and things will be fine. Thanks!

**Pull request merged**
