### PR TITLE
Opcode #135 / opcode #335

### PR DESCRIPTION
**Pull request by 4Luke4**
Added some rudimentary info about how to bypass the bug affecting these two opcodes.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Please use the relurl function as discussed, so this will work properly also for @burner1024's projects.

**Comment by 4Luke4** [comment]
> Please use the relurl function as discussed, so this will work properly also for @burner1024's projects.

Isn't that only for `yml` files...?
I edited only standard `html` files this time...

**Comment by burner1024** [comment]
To work in opcodes, relurl.html should also be included in op-list.html.

**Review by burner1024 — COMMENTED** [review]
Include before the for loop, otherwise it'll be included hundreds of times

**Comment by lynxlynxlynx** [comment]
It's fine if @burner1024 doesn't care, otherwise just adding the include doesn't change anything.

**Comment by burner1024** [comment]
At the moment opcode descriptions are not being imported. But they likely will be sooner or later.

I think it makes send to have a consistent policy for links, applying relurl everywhere.
Anyway, it's not something that's going to be done quickly, IESDP is too vast. Probably just fix them along the way while working on something else, like this pull?

**Comment by lynxlynxlynx** [comment]
I agree, that's why I proposed to use it. @4Luke4 you can search for relurl to see how it's used as a liquid filter.

**Comment by 4Luke4** [comment]
> @4Luke4 you can search for relurl to see how it's used as a liquid filter.

Will do.
Feel free to merge then...

**Comment by 4Luke4** [comment]
> Sorry, but the consensus above was to fix this now, not later, so we can get farther incrementally.

@burner1024 
OK, so what exactly...? Should I add `{% include relurl.html %}` to some other file...?

**Comment by burner1024** [comment]
I think what @lynxlynxlynx means is that urls in this pull should be changed to follow the new scheme (with relurl filter.)

**Comment by burner1024** [comment]
```html
<a name="class" href="{{ '#op337' | prepend: relurl }}">opcode #337</a>
```
"class" is just an example, for when you do want to add a name to the link, and markdown doesn't support it, and then we use html intead. You don't need to add it to every link.
And there's no need to add relurl to anchors that lead to the same page. They are relative anyway:
```html
<a href="#op337">opcode #337</a>
```
---

```html
<a name="class" href="{{ '../file_formats/ie_formats/eff_v2.htm' | prepend: relurl }}">EFF</a>
```
All urls should start from root of the site. No `../` anywhere:
```html
<a href="{{ '/file_formats/ie_formats/eff_v2.htm' | prepend: relurl }}">EFF</a>
```

**Comment by 4Luke4** [comment]
> All urls should start from root of the site. No `../` anywhere:

This leads to an error
``/file_formats/ie_formats/eff_v2.htm' not found.`

**Comment by burner1024** [comment]
Where? Push to your branch, point the eact link, I'll check.

**Comment by lynxlynxlynx** [comment]
Maybe a missing include?

**Comment by 4Luke4** [comment]
> Maybe a missing include?

Where exactly...?

**Comment by 4Luke4** [comment]
> Where? Push to your branch, point the exact link, I'll check.

Done.

The url `{{ '/file_formats/ie_formats/eff_v2.htm' | prepend: relurl }}` leads to the aforementioned error...

**Comment by 4Luke4** [comment]
> Is there an `{% include relurl.html %}` somewhere before the call in that file or where it gets included itself?

There is one in `_includes/op-list.html`...

**Comment by burner1024** [comment]
Yes, it's not working. Apparently collection `content` gets evaluated before the inclusion.

**Comment by 4Luke4** [comment]
> Yes, it's not working. Apparently collection `content` gets evaluated before the inclusion.

Ok, so what now...?

**Comment by burner1024** [comment]
I quickly tried liquify/markdownify filters, didn't help, but maybe @lynxlynxlynx has a better idea.

If eventually opcodes are going to be moved to `_data`, can just leave them as is for now, and fix later.

**Comment by lynxlynxlynx** [comment]
Put the include in the opcode file itself, then it should work.

**Comment by burner1024** [comment]
Right, except there's hundreds of them, not a very clean solution.

**Comment by lynxlynxlynx** [comment]
Most don't link anywhere, so it's fine in the interim. Easy to automatically remove when a better solution is available too.

**Comment by 4Luke4** [comment]
> Put the include in the opcode file itself, then it should work.

Done.

@burner1024 
Do you want me to remove `<code>` tags when using `<a href>`...?

**Comment by lynxlynxlynx** [comment]
op335 still needs updating

**Comment by 4Luke4** [comment]
> op335 still needs updating

Done.

**Comment by lynxlynxlynx** [comment]
Thanks and thanks for the patience!

**Comment by burner1024** [comment]
@4Luke4
- I don't particularly care.
- I do think that in most cases it's not necessary, and doesn't really add anything to the page. In some cases, maybe it actually detracts from content (like the timing mode view, which is so littered with markup that I find it hard to read).
- If you do that, thought, better put code inside the href, not the other way around. Because when you convert html to markdown, `<code><a href=x>y</a></code>` turns into `` `[x](y)` ``, which when processed by jekyll stays verbatim. Whereas `` [`x`](y) `` turns into a proper link.

@lynxlynxlynx
1. Should I send a pull adding relurl to all opcodes?
2. To be clear, is moving opcodes to data in the plan or not? If yes, I'll probably eventually send a pull for that as well, when I find the time to make the conversion. Shouldn't be too hard, considering it's pretty much structured, mostly it'll be html > markdown thing, although that could bring a few surprises.

**Comment by 4Luke4** [comment]
> * Whereas `` [`x`](y) `` turns into a proper link.

True, but then `x` will no longer be highlighted in blue...
As a result, I think I'll remove the `<code>` tags...

**Comment by burner1024** [comment]
It [should](https://github.com/Gibberlings3/iesdp/pull/129/commits/2223cc3364b9ff14d47c5c52649e8fba778e7316), though.

**Comment by 4Luke4** [comment]
> though

Yeah, me dumb: I did not update my fork to include your latest changes to `_sass/_general.scss`...

**Comment by lynxlynxlynx** [comment]
@burner1024
1. I don't think that's needed, we can do it as we start using more and more relurl.
2. You can go ahead; I see we already discussed this a bit in #84 (concluding the notes should be left inline).

**Pull request merged**
