### PR TITLE
Added definitions for PSTEE-specific opcodes

### PR DESCRIPTION
**Pull request by Argent77**
This PR provides:
- new PSTEE-specific opcode definitions using `-pstee` file suffix
- the `pstee` variable added to all existing (and new) opcode definitions

Files are configured as advised here: https://github.com/Gibberlings3/iesdp/issues/67#issuecomment-1288165288

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
The zeroing wasn't needed, but doesn't hurt.
You also need to copy and amend https://github.com/Gibberlings3/iesdp/blob/master/opcodes/pst.htm to create the listing. And the index in the same dir to make it accessible.

**Comment by Argent77** [comment]
Should I add `regenerate: true` to pstee.htm?

**Comment by lynxlynxlynx** [comment]
Hard to say, I think it was only an issue for Luke. Let's try without.

**Comment by lynxlynxlynx** [comment]
LGTM, thanks — let's see if it all works out.

**Comment by Argent77** [comment]
Looks like there's a path issue with the PST opcode references, but I don't know why. 😕

**Comment by lynxlynxlynx** [comment]
It appears relurl things we're 3 levels in for some reason. We haven't used it yet in opcodes, so this is new ground. But I see I've been beaten to the punch. :)

**Pull request merged**
