### PR TITLE
Created separate pages for PSTEE script actions, triggers, IDS files and 2DA files

### PR DESCRIPTION
**Pull request by Argent77**
This PR provides separate PST:EE pages for
- Actions: Uses `pstee` variable to control visibility.
- Triggers: Several unknowns verified by reverse engineering (thanks Bubb)
- Identifiers: Updated with content from PSTEE.
- 2DA Files: Updated with content from PSTEE.

A well as several fixes in pages for other games.

Tested with a local Jekyll installation.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
DisplayStringPoint really has different param order in bgee and pstee?

**Comment by Argent77** [comment]
Yes, parameter order for `DisplayStringPoint` is indeed different in PST:EE. There are no instances of this action found in PSTEE though, so it might as well just be a typo.

I'll check the triggers again tomorrow, but there are just very few overlaps with other games. The PSTEE-specific trigger slots are simply defined as `reserved()` in BG(2)EE and IWDEE. There may be some similarities with oPST, but I can't really test it since the game is very glitchy and unstable on my system.

I've created diffs between BGEE and PSTEE action.ids and trigger.ids definitions which helped me to create the files. I've attached them if you want to take a look yourself.

[scripting_diffs.zip](https://github.com/Gibberlings3/iesdp/files/9892227/scripting_diffs.zip)

**Comment by Argent77** [comment]
There were no overlaps with BG/IWD triggers, but I have added descriptions to PST triggers which were most likely directly mirrored in PSTEE.

**Comment by lynxlynxlynx** [comment]
Thanks, most of that matches Avenger lore as well.

**Pull request merged**
