### PR TITLE
Changed table design and prevent wrapping

### PR DESCRIPTION
**Pull request by hjred**
Added a nowrap option (supported by all major browsers; css1 property) for the table headers, thereby preventing the wrapping of smaller data cells

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
But this means they'll overflow when the container is too small, which is even worse.

**Comment by hjred** [comment]
What du you mean by overflow? These are only for the headers, not the cells

**Comment by lynxlynxlynx** [comment]
Ah, my mistake.
https://jsfiddle.net/a4ky20bc/4/

Can you kill off the other commits and either force push or open a new pr?

**Comment by hjred** [comment]
hmmm ... why is this not working .... i wanted to squash all commits into 1, since only 1 file changes ... a little puzzled

**Pull request closed without merging**
