### PR TITLE
Updated descriptions of fogarea.2da and fogpt.2da

### PR DESCRIPTION
**Pull request by Argent77**

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Do we have a better understanding of U_VEC and V_VEC? Is the horizontal/vertical reference screenwise, isometric or something else? Which way is the positive side of the axes?

**Comment by Argent77** [comment]
U and V are applied screenwise (positive U/V goes towards right/bottom screen edges). Not sure how time frame is scaled though (but I guess it's relative to frame rate).

Fog seems to be applied without taking map structures (such as wall polys or search map) into account, probably on a second pass over the final map composition.

**Comment by lynxlynxlynx** [comment]
Cool, please add that first bit to the description.

**Comment by Argent77** [comment]
Done.

**Comment by lynxlynxlynx** [comment]
Thanks!

**Pull request merged**
