### PR TITLE
SRC file format update

### PR DESCRIPTION
**Pull request by Argent77**

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Interesting. What does this weight do? Does it mean you can have several entries with the same strref and the engine will do a weighted random pick?

**Comment by Argent77** [comment]
Weight influences the probability how often an entry is picked by the engine in relation to the other entries. With two entries (`weight: 9` and `weight: 1`) the `weight: 9` entry will be picked 9 out of 10 times (on average).

**Comment by lynxlynxlynx** [comment]
Please add at least the first sentence to the description then.

**Comment by lynxlynxlynx** [comment]
Thanks!

**Pull request merged**
