### PR TITLE
Update ARE V1 animation flags

### PR DESCRIPTION
**Pull request by Argent77**
Added separate list of PSTEE-specific animation flags.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks. Which animation does it refer to? IOW how is it different from bit 8?

**Comment by Argent77** [comment]
> Which animation does it refer to? IOW how is it different from bit 8?

Creature animations (and visual effects, too).

<details>
<summary><strong>Screenshots:</strong></summary>

Flags bit 16 disabled:
Trmnt054

Flags bit 16 enabled:
Trmnt055

</details>

Flags bit 8 seems to have been changed into some kind of blending effect. But I have to test it further to be sure.

**Comment by lynxlynxlynx** [comment]
Then please add a note to bit 8 as well, that it has a different meaning. Seems like the functionality was moved to a new bit for some reason, instead of just using the new one for the new task.

**Comment by Argent77** [comment]
@lynxlynxlynx PR should be ready for merge.

**Comment by lynxlynxlynx** [comment]
Thanks!

**Pull request merged**
