### PR TITLE
Update op189.html

### PR DESCRIPTION
**Pull request by ZKArunsun**
Parameter 2's influence was said to be irrelevant. I corrected this by adding the three known values for param#2 and describing their effect.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks!

First, I think you need to add more breaks or the paramter options will be displayed in one line.

Second, the other param looks like the usual mode/type switch. Is there any documentation, proof for this weird 3rd mode (usually percentage) — what uses it? And is it a BGEE thing?

**Comment by ZKArunsun** [comment]
Yeah totally forgot the breaks. Here they are now.

There is no written proof that I know of by Beamdog or Bioware, but actually param2 already has these possible values in Near Infinity, and since they weren't documented in the IESDP, I just went and tested them for myself. I created three mages, one with no effect, one with param#1 set to 5 and param#2 set to 1, and the last with param#1 set to 5 and param#2 set to 2. and I made them cast various spells:
The first one always had the normal cast time, obviously.
The second one would cast both Magic Missile and Abi-Dalzim's Horrid Wilting in half a round.
The last one would cast Magic Missile with a normal cast time, and Abi-Dalzim's Horrid Wilting in half a round.

This wasn't really an in-depth test but it tends to confirm what's in Near Infinity. As to whether it is a BGEE thing, well it sure is a thing in BGEE, but I have no original BG game installed on my computer, so I cannot confirm anything.

**Comment by lynxlynxlynx** [comment]
Was added half a year ago:
https://github.com/NearInfinityBrowser/NearInfinity/commit/71b610a4a119ae3ed4e4b543a06339cc50ccc53d
@Argent77, any input?

**Comment by Argent77** [comment]
I don't remember exactly where I got this info. Probably from a private conversation on Beamdog Forums. Opcode modes are definitely working as described in the EE engine. Classic BG2 may not support mode=2 though.

**Comment by lynxlynxlynx** [comment]
Thanks. @ZKArunsun please update the PR:
- add a BGEE-only tag somewhere, so it's clear param2==2 behaviour is known only there
- clarify the description. NI sums it up nicely as "Set if higher", while your text  first says it's set if lower and then if it's higher than param1. Can't be usefully both.

**Comment by Argent77** [comment]
I think "Set if lower" is more suitable, as only lower speed values will be considered if mode 2 is active. I [fixed it](https://github.com/NearInfinityBrowser/NearInfinity/commit/6f66f13d156067811ed397a448b9b684d4b4fa88) in NI as well.

**Pull request merged**
